CREATE TABLE Person (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        full_name varchar(100) NOT NULL UNIQUE,
                        birth_year int NOT NULL
);

CREATE TABLE Book (
                      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title varchar(200) NOT NULL,
                      author varchar(100) NOT NULL,
                      release_year int NOT NULL,
                      person_id int REFERENCES Person(id) ON DELETE SET NULL,
                      date_taken timestamp
);

insert into person (full_name, birth_year) VALUES ('Tom', 1955);
insert into person (full_name, birth_year) VALUES ('Alex', 1968);
insert into person (full_name, birth_year) VALUES ('Ivan', 1998);
insert into person (full_name, birth_year) VALUES ('George', 1925);
insert into person (full_name, birth_year) VALUES ('Igor', 1956);
insert into person (full_name, birth_year) VALUES ('John', 1954);
insert into person (full_name, birth_year) VALUES ('Brad', 1935);
insert into person (full_name, birth_year) VALUES ('Leo', 1995);
insert into person (full_name, birth_year) VALUES ('Geralt', 1985);
insert into person (full_name, birth_year) VALUES ('Vesemir', 1975);

insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book1', 'Author1', 1820, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book2', 'Author2', 1830, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book3', 'Author3', 1840, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book4', 'Author4', 1850, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book5', 'Author5', 1860, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book6', 'Author6', 1870, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book7', 'Author7', 1880, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book8', 'Author8', 1890, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book9', 'Author9', 1900, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book10', 'Author10', 1822, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book11', 'Author11', 1823, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book12', 'Author12', 1824, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book13', 'Author13', 1825, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book14', 'Author14', 1826, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book15', 'Author15', 1827, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book16', 'Author16', 1828, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book17', 'Author17', 1829, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book18', 'Author18', 1830, null, null);
insert into Book (title, author, release_year, person_id, date_taken) VALUES ('Book19', 'Author19', 1840, null, null);